export const categories = [
  {
    label: "Front-end",
    value: "frontend",
    skills: [
      "React.js",
      "Next.js",
      "Vue.js",
      "Nuxt.js",
      "Angular",
      "Svelte",
      "Javascript",
      "Typescript",
      "HTML",
      "CSS",
      "Tailwind CSS",
      "Styled-Components",
      "Bootstrap",
      "MUI",
      "Three.js",
      "GSAP",
    ],
  },
  {
    label: "Backend",
    value: "backend",
    skills: ["PHP", "Python", "Node.js", "Go", ".Net", "Ruby", "Flask"],
  },
  {
    label: "Database",
    value: "database",
    skills: ["MySQL", "MongoDB", "PostgreSQL"],
  },
  {
    label: "Design",
    value: "design",
    skills: [
      "Figma",
      "XD Adobe",
      "Photoshop",
      "Logo",
      "3D Art",
      "2D Art",
      "UX/UI",
      "Graphic",
    ],
  },
  {
    label: "Blockchain",
    value: "blockchain",
    skills: ["Web3.js", "Solidity", "Rust"],
  },
  {
    label: "Mobile",
    value: "mobile",
    skills: ["Flutter", "React Native", "Swift"],
  },
];

export const projects = [
  {
    // category: "frontend",
    title: "EGGCELLENT NFT CLUB",
    github: "https://github.com/mosesmawuru/eggcellent-nft-club-frontend",
    live: "https://eggcellent.mosesmawuru.pro/",
    thumb: "/img/eggcellent.png",
    skills: ["React.js", "Typescript", "Styled-Components", "Web3.js"],
  },
  {
    // category: "frontend",
    title: "Gamerhub",
    github: "https://github.com/mosesmawuru/gamerhub-hackathon",
    live: "https://gamerhub.mosesmawuru.pro/",
    thumb: "/img/gamerhub.png",
    skills: [
      "React.js",
      "Next.js",
      "Typescript",
      "Styled-Components",
      "Web3.js",
    ],
  },
  {
    // category: "frontend",
    title: "Metasnails",
    github: "https://github.com/mosesmawuru/metasnail-frontend",
    live: "https://metasnail.mosesmawuru.pro/",
    thumb: "/img/metasnail.png",
    skills: ["React.js", "Tailwind CSS", "Typescript", "Styled-Components"],
  },
  {
    // category: "frontend",
    title: "Tattoo",
    github: "https://github.com/mosesmawuru/tattoo",
    live: "https://tattoo.mosesmawuru.pro/",
    thumb: "/img/tattoo.png",
    skills: ["React.js", "Typescript", "Styled-Components"],
  },
  {
    // category: "frontend",
    title: "AVID PREPARED",
    github: "https://github.com/mosesmawuru/avid-prepaid",
    live: "https://avidprepaid.mosesmawuru.pro/",
    thumb: "/img/avid.png",
    skills: ["React.js", "Tailwind CSS", "Typescript"],
  },
  {
    // category: "frontend",
    title: "Platoon - NFT Mint",
    github: "https://github.com/mosesmawuru/platoon-nft",
    live: "https://platoon.mosesmawuru.pro/",
    thumb: "/img/platoon.png",
    skills: ["Next.js", "Typescript", "Styled-Components"],
  },
  {
    // category: "frontend",
    title: "CRYPTID",
    github: "https://github.com/mosesmawuru/cryptid-nft",
    live: "https://cryptid.mosesmawuru.pro/",
    thumb: "/img/cryptid.png",
    skills: ["Next.js", "Typescript", "Styled-Components"],
  },
  {
    // category: "frontend",
    title: "Hodalica",
    github: "https://github.com/mosesmawuru/hodalica",
    live: "https://hodalica.mosesmawuru.pro/",
    thumb: "/img/hodalica.png",
    skills: ["React.js", "Typescript", "Styled-Components"],
  },
  {
    // category: "frontend",
    title: "Classe365 - LMS",
    github: "https://github.com/mosesmawuru/classe365-next.js",
    live: "https://www.classe365.com/",
    thumb: "/img/classe365.png",
    skills: ["Next.js", "Typescript", "Styled-Components"],
  },
  {
    // category: "frontend",
    title: "MintCFD",
    github: "https://github.com/wsalem117/mintcfd-ts",
    live: "https://mintcfd.com",
    thumb: "/img/mintcfd.png",
    skills: ["React.js", "MUI", "Typescript", "Python", "Flask"],
  },
  {
    // category: "frontend",
    title: "Stellar Art AI Generator",
    github: "https://github.com/wsalem117/mintcfd-ts",
    live: "https://stellar-art.vercel.app/",
    thumb: "/img/stellar.png",
    skills: ["Next.js", "Typescript", "Styled-Components", "Figma"],
  },
  {
    // category: "frontend",
    title: "Blue Wheel",
    github: "https://github.com/Typhon0130/bluewheel-app",
    live: "https://bluewheel-app.vercel.app/",
    thumb: "/img/bluewheel.png",
    skills: ["React.js", "Styled-Components"],
  },
  {
    // category: "frontend",
    title: "Devscale AI",
    github: "https://github.com/Typhon0130/devscale-ai",
    live: "https://devscale-ai.vercel.app/",
    thumb: "/img/devscale.png",
    skills: ["Next.js", "Styled-Components", "Node.js"],
  },
  {
    // category: "frontend",
    title: "Bitsports - Play to Earn",
    github: "https://github.com/bitsportgaming/bitsport-bitpool-frontend",
    live: "https://play.bitpool.gg/",
    thumb: "/img/bitsports.png",
    skills: [
      "Next.js",
      "Tailwind CSS",
      "Typescript",
      "Node.js",
      "MongoDB",
      "Web3.js",
      "Solidity",
    ],
  },
  {
    // category: "frontend",
    title: "Listsy",
    github: "https://github.com/crazy0629/listsy_frontend",
    live: "http://44.192.100.83:4000/",
    thumb: "/img/metasnail.png",
    skills: [
      "Next.js",
      "Styled-Components",
      "Typescript",
      "Node.js",
      "MongoDB",
    ],
  },
  {
    // category: "frontend",
    title: "Hayami NFT",
    github: "https://github.com/cupid20103/hayami",
    live: "https://www.hayami.world/",
    thumb: "/img/hayami.png",
    skills: [
      "React.js",
      "Styled-Components",
      "Typescript",
      "Web3.js",
      "Solidity",
    ],
  },
  {
    // category: "frontend",
    title: "Job Wizard Chrome extension",
    github: "https://github.com/crazy0629/listsy_frontend",
    live: "https://chromewebstore.google.com/detail/jobwizard-job-application/kbhgdbfkbgkokgkkdhnnlmkhnokjmfib",
    thumb: "/img/jobwizard.png",
    skills: ["Javascript", "HTML", "CSS"],
  },
];
